export const dashboardCopy = {
  en: {
    accountEyebrow: "Your FitTrack account",
    welcome: "Welcome",
    intro: "See how you are progressing, update your goal, and keep your nutrition plan aligned with your current needs.",
    changePassword: "Change password",
    personalize: "Personalize",
    matchTitle: "Keep your plan matched to you",
    summary: { weight: "Weight", target: "Target", plan: "Plan", goal: "Goal", days: "7 days", none: "None" },
    settingsEyebrow: "Plan settings",
    settingsTitle: "Update weight and goal",
    settingsText: "Your calories and existing portions update automatically.",
    currentWeight: "Current weight",
    currentGoal: "Current goal",
    activityLevel: "Activity level",
    selectActivity: "Select activity",
    activities: ["Sedentary", "Light · 1–3 days/week", "Moderate · 3–5 days/week", "High · 6–7 days/week", "Very high / physical job"],
    using: "Using",
    years: "years",
    currentMaintenance: "current maintenance",
    noCalculator: "No calculator profile found in this browser.",
    completeCalculator: "Complete the calculator →",
    updating: "Updating…",
    updatePlan: "Update my plan",
    saveTarget: "Save new target",
    noCurrentPlan: "No current meal plan",
    generatePlan: "Generate your plan →",
    goals: { lose: "Lose weight", maintain: "Maintain weight", gain: "Gain weight" },
    messages: {
      browserData: "Some saved browser data could not be read. Open the calculator or meal plan to refresh it.",
      invalidWeight: "Enter a valid weight between 20 and 500 kg.",
      calculatorFirst: "Complete the calorie calculator first so FitTrack can recalculate your calorie target accurately.",
      selectActivity: "Select your current activity level.",
      incompleteProfile: "Your calculator profile is incomplete. Add age, height, gender, and activity level in the calculator first.",
      syncFailed: "Your browser plan was updated, but account sync failed",
      planUpdated: (calories: number) => `Updated to ${calories} kcal/day. Your current plan portions and account details have been adjusted.`,
      targetSaved: (calories: number) => `Weight and goal saved. Your new target is ${calories} kcal/day; generate a meal plan to apply it.`,
    },
    progress: {
      eyebrow: "Your progress", title: "Progress dashboard", latest: "Latest entries",
      currentWeight: "Current weight", firstWeighIn: "Add your first weigh-in", fromPrevious: "from previous",
      dailyTarget: "Daily target", appliedPlan: "Applied to your meal plan", completeCalculator: "Complete your calculator",
      proteinRange: "Protein range", recommended: "Recommended per day",
      currentGoal: "Current goal", activePlan: "7-day plan active", noActivePlan: "No active plan yet",
      weightTrend: "Weight trend", lastWeighIns: "recorded weigh-ins", chartLabel: "Recent weight chart",
      chartEmpty: "Update your weight below to start the chart.", dailyNutrition: "Daily nutrition",
      nutritionAverage: "Average from your current plan", perDay: "kcal / day", protein: "Protein", carbs: "Carbs", fat: "Fat", noPlan: "No plan",
    },
    preferences: {
      eyebrow: "Meal preferences", title: "Favorite meals",
      selectedText: (count: number) => `${count} meals will be prioritized in your next plan.`,
      emptyText: "Choose meals you enjoy and build your next plan around them.",
      close: "Close ↑", choose: "Choose meals ↓", search: "Search meals or ingredients",
      allMeals: "All meals", breakfast: "Breakfast", lunch: "Lunch", dinner: "Dinner", snack: "Snack", allDiets: "All diets",
      protein: "protein", noMatches: "No meals match these filters.", selected: "selected",
      saving: "Saving…", create: "Create plan from selected meals", chooseOne: "Choose at least one meal you like.",
    },
    compactPlan: { eyebrow: "Current plan", title: "Seven-day overview", open: "Open →", day: "Day", meals: "meals" },
    helpful: {
      eyebrow: "Your FitTrack", title: "Tools and resources", aria: "FitTrack tools",
      links: [
        ["Calculator", "Update body details and calorie needs", "Your details"],
        ["Full meal plan", "View portions, recipes, and shopping list", "Nutrition"],
        ["Workout programs", "Find training matched to your preferences", "Training"],
        ["Recipe library", "Browse all available meals", "Recipes"],
        ["Nutrition guides", "Compare popular eating approaches", "Guides"],
      ],
    },
  },
  bg: {
    accountEyebrow: "Твоят FitTrack акаунт",
    welcome: "Здравей",
    intro: "Проследявай напредъка си, обновявай целта си и поддържай хранителния план съобразен с текущите си нужди.",
    changePassword: "Смени паролата",
    personalize: "Персонализирай",
    matchTitle: "Поддържай плана съобразен с теб",
    summary: { weight: "Тегло", target: "Целеви калории", plan: "План", goal: "Цел", days: "7 дни", none: "Няма" },
    settingsEyebrow: "Настройки на плана",
    settingsTitle: "Обнови теглото и целта",
    settingsText: "Калориите и текущите порции се обновяват автоматично.",
    currentWeight: "Текущо тегло",
    currentGoal: "Текуща цел",
    activityLevel: "Ниво на активност",
    selectActivity: "Избери активност",
    activities: ["Заседнал начин на живот", "Лека · 1–3 дни седмично", "Умерена · 3–5 дни седмично", "Висока · 6–7 дни седмично", "Много висока / физическа работа"],
    using: "Използвани данни",
    years: "години",
    currentMaintenance: "текущо поддържане",
    noCalculator: "В този браузър няма запазени данни от калкулатора.",
    completeCalculator: "Попълни калкулатора →",
    updating: "Обновяване…",
    updatePlan: "Обнови плана ми",
    saveTarget: "Запази новата цел",
    noCurrentPlan: "Няма текущ хранителен план",
    generatePlan: "Създай своя план →",
    goals: { lose: "Сваляне на тегло", maintain: "Поддържане", gain: "Качване на тегло" },
    messages: {
      browserData: "Част от запазените данни не могат да бъдат прочетени. Отвори калкулатора или хранителния план, за да ги обновиш.",
      invalidWeight: "Въведи валидно тегло между 20 и 500 кг.",
      calculatorFirst: "Първо попълни калорийния калкулатор, за да изчислим точно новата ти цел.",
      selectActivity: "Избери текущото си ниво на активност.",
      incompleteProfile: "Данните в калкулатора са непълни. Добави възраст, височина, пол и активност.",
      syncFailed: "Планът в браузъра е обновен, но синхронизирането с акаунта е неуспешно",
      planUpdated: (calories: number) => `Планът е обновен до ${calories} kcal на ден. Порциите и данните в акаунта са коригирани.`,
      targetSaved: (calories: number) => `Теглото и целта са запазени. Новата ти цел е ${calories} kcal на ден; създай хранителен план, за да я приложиш.`,
    },
    progress: {
      eyebrow: "Твоят напредък", title: "Табло за напредъка", latest: "Последни записи",
      currentWeight: "Текущо тегло", firstWeighIn: "Добави първото си измерване", fromPrevious: "спрямо предишното",
      dailyTarget: "Дневна цел", appliedPlan: "Приложена към хранителния план", completeCalculator: "Попълни калкулатора",
      proteinRange: "Диапазон протеин", recommended: "Препоръчително на ден",
      currentGoal: "Текуща цел", activePlan: "Активен 7-дневен план", noActivePlan: "Все още няма активен план",
      weightTrend: "Промяна в теглото", lastWeighIns: "последни измервания", chartLabel: "Графика на последните измервания",
      chartEmpty: "Обнови теглото си по-долу, за да започнеш графиката.", dailyNutrition: "Дневно хранене",
      nutritionAverage: "Средно от текущия ти план", perDay: "kcal / ден", protein: "Протеин", carbs: "Въглехидрати", fat: "Мазнини", noPlan: "Няма план",
    },
    preferences: {
      eyebrow: "Предпочитания за ястия", title: "Любими ястия",
      selectedText: (count: number) => `${count} ястия ще бъдат с приоритет в следващия ти план.`,
      emptyText: "Избери ястия, които харесваш, и създай следващия си план около тях.",
      close: "Затвори ↑", choose: "Избери ястия ↓", search: "Търси ястия или съставки",
      allMeals: "Всички ястия", breakfast: "Закуска", lunch: "Обяд", dinner: "Вечеря", snack: "Снакс", allDiets: "Всички диети",
      protein: "протеин", noMatches: "Няма ястия с тези филтри.", selected: "избрани",
      saving: "Запазване…", create: "Създай план с избраните ястия", chooseOne: "Избери поне едно ястие, което харесваш.",
    },
    compactPlan: { eyebrow: "Текущ план", title: "Преглед на седемте дни", open: "Отвори →", day: "Ден", meals: "ястия" },
    helpful: {
      eyebrow: "Твоят FitTrack", title: "Инструменти и ресурси", aria: "FitTrack инструменти",
      links: [
        ["Калкулатор", "Обнови данните за тялото и нужните калории", "Твоите данни"],
        ["Пълен хранителен план", "Виж порциите, рецептите и списъка за пазаруване", "Хранене"],
        ["Тренировъчни програми", "Намери тренировка според предпочитанията си", "Тренировки"],
        ["Библиотека с рецепти", "Разгледай всички налични ястия", "Рецепти"],
        ["Хранителни режими", "Сравни популярни подходи към храненето", "Насоки"],
      ],
    },
  },
} as const;

export type DashboardLanguage = keyof typeof dashboardCopy;
